/** Standardized error codes across all DUM360 services. */
export const ErrorCode = {
	// Auth
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	INVALID_TOKEN: "INVALID_TOKEN",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	INVALID_REGISTRATION_TOKEN: "INVALID_REGISTRATION_TOKEN",

	// Resource
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",
	ALREADY_EXISTS: "ALREADY_EXISTS",

	// Validation
	VALIDATION_FAILED: "VALIDATION_FAILED",
	INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",

	// Rate Limiting
	RATE_LIMITED: "RATE_LIMITED",

	// Task
	TASK_NOT_FOUND: "TASK_NOT_FOUND",
	TASK_ALREADY_TERMINAL: "TASK_ALREADY_TERMINAL",
	NODE_NOT_AVAILABLE: "NODE_NOT_AVAILABLE",
	NO_CAPABLE_NODE: "NO_CAPABLE_NODE",

	// Node
	NODE_NOT_FOUND: "NODE_NOT_FOUND",
	NODE_OFFLINE: "NODE_OFFLINE",
	NODE_EVICTED: "NODE_EVICTED",

	// Infrastructure
	DATABASE_ERROR: "DATABASE_ERROR",
	QUEUE_ERROR: "QUEUE_ERROR",
	ELASTICSEARCH_ERROR: "ELASTICSEARCH_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
